version: 1.0.{build}
image:
- Visual Studio 2019
- Visual Studio 2017
configuration: Release
platform: x64
before_build:
- cmd: >-
    cmake --version

    cmake -B build


build_script:
- cmake --build build --config Release --parallel

after_build:
- cmd: 7z a pcm-all.zip %APPVEYOR_BUILD_FOLDER%\build\bin\Release\*.exe %APPVEYOR_BUILD_FOLDER%\build\bin\Release\*.dll %APPVEYOR_BUILD_FOLDER%\build\src\Release\*.lib %APPVEYOR_BUILD_FOLDER%\build\src\Release\*.exp
artifacts:
- path: pcm-all.zip
  name: pcm-all